---
- name: Configure Ubuntu 22.04
  hosts: all
  become: yes

  tasks:
    - name: Check OS version and architecture
      import_tasks: ./func/check_os.yml

    - name: Overwrite resolv.conf with Google DNS
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 8.8.8.8
          nameserver 8.8.4.4
        mode: '0644'


    - name: Ensure apt cache is up-to-date
      apt:
        update_cache: yes

    - name: Install unzip
      apt:
        name: unzip
        state: present

