---
- name: Install and configure Grafana
  hosts: all
  become: yes
  tasks:
    - name: Download Grafana GPG key
      ansible.builtin.apt_key:
        url: https://apt.grafana.com/gpg.key
        state: present
        keyring: /usr/share/keyrings/grafana.key

    - name: Add Grafana APT repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main"
        filename: grafana
        state: present

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Grafana
      ansible.builtin.apt:
        name: grafana
        state: present

    - name: Enable Grafana service
      ansible.builtin.systemd:
        name: grafana-server
        enabled: yes
        state: started

    - name: Check Grafana service status
      ansible.builtin.systemd:
        name: grafana-server
        state: started
        enabled: yes
        daemon_reload: yes
